#!/bin/bash
if  [ $# -eq 1 ];then
      if  [ -f "$1" ];then
          while read username ;do
	      useradd -s /bin/false $username &>/dev/null
	  done < $1
      else
          echo "Input file not found"
	  exit 1
      fi
else
     echo "Usage: /root/barchusers userfile"
     exit 2
fi
